### ISSUE TITLE
Enhance Functionality by Adding host_details Feature and Refactoring Code to Improve Maintainability

### ISSUE THREAD

**Issue by arieg88** [johnbalvin/pyairbnb#1]
I've made two improvements to the project that could enhance functionality and maintainability:

- Adding host_details: I’ve implemented a new feature that allows for the retrieval of host details for listings. This can be useful for users who want to access more comprehensive information about the listing’s host. I’ve tested this feature using the provided tests, except for the test that uses the proxy, and it’s working fully functional.

- Refactoring Code to Remove Redundant Lines: While working on the feature, I also noticed that there were some repetitive code blocks in the functions, making the code harder to maintain and extend. I’ve refactored these sections to improve readability and reduce redundancy, making the code easier to maintain in the future.

You can find the first change (the host_details feature) in the main branch of my fork. Both changes are available under the branch refactor-functions. If you're interested, I’d be happy to open a pull request with these improvements for your review."

**Comment by johnbalvin** [comment]
Thanks for the contribution, if you dont mind please create a pull request
