### ISSUE TITLE
Only 40 results, is there a pagination ?

### ISSUE THREAD

**Issue by younesbs7** [johnbalvin/pyairbnb#3]

**Comment by johnbalvin** [comment]
The pagination is by default on the function `search_all`

could you please send an example of your search, I'm getting 200+ results with these parameters:

```
currency = "USD"  # Currency for the search
check_in = "2025-01-01"  # Check-in date
check_out = "2025-01-04"  # Check-out date
ne_lat = 26.244992525492258  # North-East latitude
ne_long = -80.20554283078371  # North-East longitude
sw_lat = 26.052735877248157 # South-West latitude
sw_long = -80.39148365866907  # South-West longitude
zoom_value = 12  # Zoom level for the map
```

**Comment by younesbs7** [comment]
I didn't find any function named search_all, but rather 'get' > Below the code I used :

import json
from pyairbnb.search import get

# Define search parameters
currency = "USD"
check_in = "2025-01-01"
check_out = "2025-01-04"
ne_lat = 26.244992525492258
ne_long = -80.20554283078371
sw_lat = 26.052735877248157
sw_long = -80.39148365866907
zoom_value = 12
cursor = "" 
api_key = "my_api_key"
proxy_url = "" 

# Fetch results using the `get` function
try:
    results = get(
        check_in, check_out, ne_lat, ne_long, sw_lat, sw_long, zoom_value, cursor, currency, api_key, proxy_url
    )
    
    # Parse the results if it's a string
    if isinstance(results, str):
        results = json.loads(results)  # Parse JSON string into a dictionary

    # Extract listing names
    listing_names = []
    search_results = results.get("searchResults", [])  # Safely access the search results
    for result in search_results:
        listing = result.get("listing", {})
        if "name" in listing:
            listing_names.append(listing["name"])

    # Display listing names with rankings
    if listing_names:
        for rank, name in enumerate(listing_names, start=1):
            print(f"{rank}. {name}")
    else:
        print("No valid listings found.")

except Exception as e:
    print(f"An error occurred: {e}")


And this is the result I got :
1. Self checkin Private master room / private bath
2. Local attractions nearby Room4/
17min from FLL- AP
3. Welcome at Quiet ROOM for REST
4. Miami home near Sawgrass
5. Charming Home with Private Balcony.
6. Peaceful Private Room Retreat
7. Walking Distance to Sawgrass Mall
8. Best Tourist Destination, Close to SawgrassMall
9. SawgrassMallHome
10. Luxury Villa Heated Pool +Pickleball/BKB/Soccer CT
11. Spacious! In room TV/min to Beach/Shopping&Airprt
12. Steps to Hardrock! Managed by BNR Vacation Rentals
13. Blue Room in Garden Estate House
14. Cozy, relaxing & beautiful condo for two.
15. Exquisite Pineapple Townhouse Steps from Sawgrass
16. Delightful room ❤-near Sawgrass w/private bathroom
17. Cosy Room for Rent
18. Impecable min airport/beach/shops
19. Stylish New Hotel!
20. Single Travelers feel safe in my home!
21. Spacious and comfortable room
22. SAWGRASS MILLS MALL BEAUTIFUL ROOM
23. Stay & Shop Till You Drop!
24. Coliving Nordic Room3
25. A piece of Jamaica in Ft Lauderdale
26. Adorable 1-bedroom suite with free parking.
27. Private bdrm&bath/own entrance
28. Comfy home w/ Sunset+Pool & lake
29. Spacious Suite w/t Queen Bed no balcony
30. Villa Joy
31. SAWGRASS BEAUTIFUL ROOM WAKING DIST TO MALL
32. Private Calm Guesthouse/ Sunrise
33. Habitación bella con todo
34. Spacious 3BR Family-Friendly Home Near Attractions
35. Luxury+ Fun | Heated POOL | Games | 15 min to FLL
36. Charming 2BR Lakefront Cottage in Davie near Beach
37. Relax and Unwind! Kitchenette, Pool, FREE Parking!
38. 2/2 Accommodation in Sunrise, Florida
39. Cozy Comfy Private Master Suite in the Burbs
40. Tia's Place - 1

**Comment by johnbalvin** [comment]
you need to use `search_all ` function, for example:

```
import pyairbnb
import json

# Define search parameters
currency = "USD"
check_in = "2025-01-01"
check_out = "2025-01-04"
ne_lat = 26.244992525492258
ne_long = -80.20554283078371
sw_lat = 26.052735877248157
sw_long = -80.39148365866907
zoom_value = 12

# Search listings within specified coordinates and date range
search_results = pyairbnb.search_all(check_in, check_out, ne_lat, ne_long, sw_lat, sw_long, zoom_value, currency, "")

# Save the search results as a JSON file
with open('search_results.json', 'w', encoding='utf-8') as f:
    f.write(json.dumps(search_results))  # Convert results to JSON and write to file
```

**Comment by younesbs7** [comment]
Got it, thanks. Took me some time to understand the function, but all good now.

I still quite don't understrand the need of zoom_value.

I understand what it represents, but don't really see difference in results when using 1 or 12.

**Comment by johnbalvin** [comment]
I haven't checked deeply but airbnb server requires to send that value
